organism: Bacillus
model_type: HotCNNHyperModel
cv: 5
epochs: 50
n_samples: 1
bach_size: 32
fasta_dir: fasta
weights_dir: weights
best_weights_dir: best_weights
base_results_dir: results
debug: 1
data:
  - k: 1
    encode: label
    slice: [59, 20, 20]
  - k: 2
    encode: label
    slice: [59, 20, 20]
hypermodel:
  execution_per_trial: 3
  hyperband_max_epochs: 30